[package]
name = "notes-index"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
meilisearch-sdk = "0.27.1"
serde = "1.0.217"
serde_json = "1.0.138"
itertools = "0.14.0"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
